## Zip function

In [7]:
languages = ['Java', 'Python', 'JS']
versions = [14, 5, 9]


In [8]:
result = zip(languages, versions)

In [9]:
result

In [10]:
list(result)

[('Java', 14), ('Python', 5), ('JS', 9)]

## Pandas

In [11]:
data = {
    'Name': ['a', 'b', 'c'],
    'Age': [2, 3, 4]
}

In [12]:
import pandas as pd
df = pd.DataFrame(data)

In [13]:
df

Name  Age
0    a    2
1    b    3
2    c    4

## Convert to series

In [14]:
dfName = df['Name']

In [15]:
dfName

0    a
1    b
2    c
Name: Name, dtype: object

In [16]:
type(dfName)

pandas.core.series.Series

## lambda function

In [17]:
r = df['Age'].apply(lambda x:21 if x == 2 else x)

In [18]:
r

0    21
1     3
2     4
Name: Age, dtype: int64

## Numpy

### Array creation functions

In [19]:
import numpy as np
arr = np.array([1,2,46,7])
print(arr)

[ 1  2 46  7]


In [20]:
arr_zeros = np.zeros((3,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr_ones = np.ones((3,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Array Manipulation function

In [22]:
arr1 = np.array([1,3,5,7,9,11])

In [23]:
# Reshape 1D array to 2D array
arr_reshape = np.reshape(arr1, (2,3))

In [24]:
arr_reshape

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [25]:
# Transpose the 2D array
arr_trans = np.transpose(arr_reshape)
arr_trans

array([[ 1,  7],
       [ 3,  9],
       [ 5, 11]])

### Array Input and Output function

In [26]:
arr_n = np.array([
    [1,3,5],
    [2,4,6]
])

In [27]:
# save the array to a text file
np.savetxt('data.txt', arr_n)

In [28]:
# load the data from text file
loaded_data = np.loadtxt('data.txt')

In [29]:
print(loaded_data)

[[1. 3. 5.]
 [2. 4. 6.]]


# Scikit-learn

In [30]:
# SciPy has optimised functions that used in  NunPy and Data Science
# 2x + y = 5
# 4x - 5y = 7
from scipy import linalg

In [31]:
a = np.array([[2,1], [4,-5]])
b = np.array([[5], [7]])
x = linalg.solve(a,b)

In [32]:
# To check if result is zero or non-zero
print(a.dot(x)-b)

[[0.]
 [0.]]


In [33]:
# 2x + y = 5
# x - 3y = -2

a = np.array([[2,1], [1,-3]])
b = np.array([[5], [-2]])
x = linalg.solve(a,b)

In [34]:
print(a.dot(x)-b)

[[ 0.0000000e+00]
 [-4.4408921e-16]]
